package com.example.backend.enums;

public enum MessageKey {
    USER_NOT_FOUND,
    VEHICLE_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    CATEGORY_ALREADY_EXISTS,
    NOTIFICATION_NOT_FOUND,
    NOTIFICATION_MARKED_READ,
    ALL_NOTIFICATIONS_MARKED_READ,
    SERVICE_HISTORY_CREATED,
    PREMATURE_REPLACEMENT_DETECTED,
    SERVICE_HISTORY_NOT_FOUND
}